# Tensor

In [2]:
# tensor 생성
import torch

print(torch.Tensor([[1,2,3], [4,5,6]]))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
# tensor 속성
tensor = torch.rand(1,2)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([1, 2])
torch.float32
cpu


In [5]:
# 차원 변환
tensor = tensor.reshape(2, 1)
print(tensor)

tensor([[0.0286],
        [0.1720]])


### 자료형 설정
텐서는 디폴트 float인데, tensor.float보다 많은 메모리를 차지함.  
학습 과정에서의 효율을 위해 텐서를 선언할 때는 가능한 한 torch.* 형태로 자료형을 지정해야 한다.



In [6]:
tensor = torch.rand((3, 3), dtype=torch.float)
print(tensor)

tensor([[0.0643, 0.3506, 0.6705],
        [0.4468, 0.9274, 0.7679],
        [0.4506, 0.4685, 0.7736]])


### 장치 설정

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"
cpu = torch.FloatTensor([1, 2, 3])
gpu = torch.cuda.FloatTensor([1, 2, 3])
tensor = torch.rand((1, 1), device=device)

print(device)
print(cpu)
print(gpu)
print(tensor)

/tmp/ipython-input-3798038277.py:3: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:78.)
  gpu = torch.cuda.FloatTensor([1, 2, 3])


cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.4062]], device='cuda:0')


### 장치 변환
cpu, gpu를 사용하는 텐서들은 상호간 연산이 불가능하다.  
cpu 텐서 <-> numpy : 가능  
gpu 텐서 <-> numpy : 불가능  
그래서 넘파이 배열 데이터를 학습시키려면 gpu 장치로 변환해야 한다.